services:
  - type: web
    name: nissan-epower-diagnostic
    runtime: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: MANUAL_PDF
        value: nissan-xtrail-epower-2024-ht33-e1-4wd.pdf
